CREATE TABLE users (
  user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL,
  password TEXT NOT NULL,
  user_email TEXT,
  first_name TEXT,
  middle_name TEXT,
  last_name TEXT,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);
